env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - google
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules:
  max-len: ['warn', 128]
  complexity: ['error', 10]
  react/prop-types: off
